/*
!!! ATTENTION !!!
THIS FILE HAS BEEN AUTO-GENERATED
DO NOT EDIT THIS FILE
*/

// Imports 
import { AppConfig, api as axios } from 'hirovo-config'; 
import { ApiService } from '../../../../services';

// Custom Types 
type Guid = string; 
type Double = number;

// Settings...

export namespace HirovoAPI {

	export namespace Enums {

	}

	export namespace Workers {

		export namespace Detail {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/Detail';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
			}
			export interface IResponseModel {
				id: Guid;
				description: string;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isAvailable?: boolean;
			}
		}

		export namespace UpdateProfile {
			export const RequestPath = AppConfig.HirovoUrl + '/Workers/UpdateProfile';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				description: string;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isAvailable?: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

	export namespace Jobs {

		export namespace UpdateProfile {
			export const RequestPath = AppConfig.HirovoUrl + '/Jobs/UpdateProfile';
			export const Request = (data: IRequestModel) => ApiService.call<IResponseModel>(axios.post(RequestPath,{...data}));
			export interface IRequestModel {
				userId: Guid;
				description: string;
				phoneNumber: string;
				birthDate?: Date;
				city: string;
				district: string;
				isAvailable?: boolean;
			}
			export interface IResponseModel {
				id: Guid;
			}
		}

	}

}